SELECT 
'fdlz-datascience' as "Cluster"
,TO_DATE("start"/1000) as "startDate"
,TO_TIMESTAMP("start"/1000) as "startTimeSecond"
,DATE_TRUNC('MINUTE', CAST("start" as TIMESTAMP)) as "startTimeMinute"
,TO_DATE("start"/1000) as "finishDate"
,"finish" - "start" AS "totalDurationMS"
,1 as QueryCount
,CASE WHEN username = '$dremio$' THEN 'System' ELSE 'User' END as job_type,
CASE WHEN outcomeReason IS NULL THEN 'O|No error'
  WHEN outcomeReason IN ('-1','0','10','33','43','49','at index 0','at index 1','at index 2','at index 3','at index 4','at index 5','at index 6','at index 7','at index 9','at index 9','Index: 0, Size: 0','Index: 3, Size: 3','VARCHAR','BOOLEAN','Canceled') THEN 'D|Meaningless errors (-1, 0, 1, 10, 33, 43, 49, Canceled, VARCHAR etc.)'
  WHEN outcomeReason = 'ConnectException: Connection refused' THEN '?|ConnectException: Connection refused'
  WHEN outcomeReason = 'NullPointerException' then 'D|NPE: Just NullPointerException'
  WHEN outcomeReason = 'Statement preparation aborted' then '?|Statement preparation aborted'
  WHEN outcomeReason = 'Unable to start resources within requested time.' then '?|Unable to start resources within requested time.'
  WHEN outcomeReason = 'Reflection has been updated since reflection was scheduled.' then 'U|Reflection has been updated since reflection was scheduled.'
  WHEN outcomeReason = 'Failure parsing the query.' then 'U|Failure parsing the query.'
  WHEN outcomeReason = 'ORDER BY expression should not contain OVER clause' then 'U|ORDER BY expression should not contain OVER clause'
  WHEN outcomeReason = 'Flatten does not support empty list.' then 'U|Flatten does not support empty list.'
  WHEN outcomeReason = 'Failed to get rel from the request' then '?|Failed to get rel from the request'
  WHEN outcomeReason = 'There is no row access policy to drop' then 'U|There is no row access policy to drop'
  WHEN (POSITION('Object ''' in outcomeReason) = 1 AND POSITION(''' not found' in outcomeReason) = (LENGTH(outcomeReason) - LENGTH(''' not found') + 1))
    OR (POSITION('SqlValidatorException: Object ''' in outcomeReason) = 1 AND POSITION(''' not found' in outcomeReason) = (LENGTH(outcomeReason) - LENGTH(''' not found') + 1))
    OR (POSITION('Object ''' in outcomeReason) = 1 AND POSITION(' not found within'  in outcomeReason) > 0) then 'U|Object O not found'
  WHEN (POSITION('Table ''' in outcomeReason) = 1 AND POSITION(''' not found' in outcomeReason) = (LENGTH(outcomeReason) - LENGTH(''' not found') + 1)) then 'U|Table T not found'
  WHEN POSITION('Failed to drop table: ' in outcomeReason) = 1 then 'U|Failed to drop table (MultiObjectDeleteException?)' 
  WHEN POSITION('Folder ' in outcomeReason) = 1 AND POSITION(' already exists' in outcomeReason) > 0 then 'U|Folder F already exists' 
  WHEN POSITION('(io.grpc.StatusRuntimeException) UNKNOWN' in outcomeReason) > 0 AND POSITION('com.dremio.service.catalog.DatasetCatalogServiceGrpc$DatasetCatalogServiceBlockingStub.getDataset()' in outcomeReason) > 0 then 'D|DatasetCatalogServiceBlockingStub.getDataset() ServiceRuntimeException' 
  WHEN POSITION('Partition ''' in outcomeReason) > 0 AND POSITION(''' does not exist in ' in outcomeReason) > 0 then 'U|Partition P does not exist' 
  WHEN POSITION('The file /samples.dremio.com' in outcomeReason) > 0 AND POSITION('is not in Parquet format' in outcomeReason) > 0 then 'U|SPECIAL: Old Parquet samples need to be repromoted as Iceberg tables (not in Parquet format)' 
  WHEN POSITION('FileNotFoundException: File dremioAzureStorage://:/uscdotpdprojectstore/metadata/' in outcomeReason) > 0 OR POSITION('FileNotFoundException: File dremioAzureStorage://:/dremiocloudafcustdev/metadata/' in outcomeReason) > 0 then 'U|SPECIAL: PWC metadata issues' 
  WHEN POSITION('metadata.json does not exist in the following directory: /uscdotpdprojectstore/metadata/' in outcomeReason) > 0 then 'U|SPECIAL: PWC empty project store (FileNotFoundException)' 
  WHEN POSITION('hello_world.txt is not in Parquet format' in outcomeReason) > 0 then 'U|SPECIAL: Moderna''s invalid table format (hello_world.txt is not in Parquet format)'
  WHEN POSITION('Dremio does not support casting or coercing' in outcomeReason) > 0 THEN 'U|Dremio does not support casting or coercing'
  WHEN POSITION('Please check the size and format of the files you are promoting and select the format from the dropdown box accordingly' in outcomeReason) > 0 THEN 'U|The file <file> is not in Parquet format'
  WHEN POSITION('Reflection could not be created as it uses context-sensitive functions. Functions like IS_MEMBER, USER, etc. cannot be used in reflections since they require context to complete.' in outcomeReason) > 0 THEN 'U|Reflection could not be created as it uses context-sensitive functions'
  WHEN POSITION('Query canceled - out of memory, check the query profile for details' in outcomeReason) > 0 THEN '?|Query cancelled by coordinator heap monitor (memory)'
  WHEN POSITION('Query canceled by executor heap monitor' in outcomeReason) > 0 THEN '?|Query cancelled by executor heap monitor (memory)'
  WHEN POSITION('Heap monitor detected that the heap is almost full' in outcomeReason) > 0 THEN '?|Query cancelled by executor heap monitor (memory)'
  WHEN POSITION('MemoryArbiter detected no memory available' in outcomeReason) > 0 THEN '?|MemoryArbiter detected no memory available (memory)'
  WHEN POSITION('Query canceled by MemoryArbiter' in outcomeReason) > 0 THEN '?|Query cancelled by MemoryArbiter (memory)'
  WHEN POSITION('(io.netty.util.internal.OutOfDirectMemoryError) failed to allocate' in outcomeReason) > 0 THEN '?|OutOfDirectMemoryError: failed to allocate x byte(s) of direct memory (memory)'
  WHEN POSITION('Query cancelled by user' in outcomeReason) > 0 THEN 'U|Query cancelled by user'
  WHEN POSITION('host=wizard-prod-replica-2.cn3ixam1w40x.eu-west-2.rds.amazonaws.com' in outcomeReason) > 0 THEN 'U|Merlin: Failure getting source [MySQL Prod]'
  WHEN POSITION('] uses an unsupported file format' in outcomeReason) > 0 THEN 'U|AWS Glue table [<table>] uses an unsupported file format'
  WHEN POSITION('Failed to spill to disk. Please check space availability' in outcomeReason) > 0 THEN 'U|Failed to spill to disk. Please check space availability'
  WHEN POSITION('Function ''{fn locate}'' is not defined' in outcomeReason) > 0 THEN 'U|Function ''{fn locate}'' is not defined'
  WHEN POSITION('Illegal use of ''NULL''' in outcomeReason) > 0 THEN 'U|Illegal use of ''NULL'''
  WHEN POSITION('Incremental refresh did not find previous DONE materialization' in outcomeReason) > 0 THEN 'U|Incremental refresh did not find previous DONE materialization'
  WHEN POSITION('Job was cancelled because the query went beyond system capacity during query planning.' in outcomeReason) > 0 THEN 'L|Job was cancelled because the query went beyond system capacity during query planning.'
  WHEN POSITION('No executors are available for data with hard affinity. You may consider using "registration.publish-host" property if your network rules change.' in outcomeReason) > 0 THEN '?|No executors are available for data with hard affinity. You may consider using "registration.publish-host" property if your network rules change.'
  WHEN POSITION('No matching reflection found.' in outcomeReason) > 0 THEN 'U|No matching reflection found.'
  WHEN POSITION('Not authorized to use external query.' in outcomeReason) > 0 THEN 'U|Not authorized to use external query.'
  WHEN POSITION('query cost too hgih >=' in outcomeReason) > 0 THEN 'U|query cost too hgih >='
  WHEN POSITION('Query was rejected based on a rule that did not specify a rejection reason.' in outcomeReason) > 0 THEN 'U|Query was rejected based on a rule that did not specify a rejection reason'
  WHEN POSITION('RpcException: Timeout while waiting for client to be in ready state.' in outcomeReason) > 0 THEN '?|RpcException: Timeout while waiting for client to be in ready state'
  WHEN POSITION('Selective refresh is not allowed on unknown datasets. Please run full refresh on' in outcomeReason) > 0 THEN 'U|Selective refresh is not allowed on unknown datasets. Please run full refresh on <dataset>'
  WHEN POSITION('System user is not allowed to execute queries via UI. Please use your own user account instead.' in outcomeReason) > 0 THEN 'U|System user is not allowed to execute queries via UI'
  WHEN POSITION('Unable to find any files for datasets.' in outcomeReason) > 0 THEN 'U|Unable to find any files for datasets'
  WHEN POSITION('Unable to get Hive table InputFormat class. There is neither InputFormat class explicitly specified nor a StorageHandler class provided.' in outcomeReason) > 0 THEN 'U|Unable to get Hive table InputFormat class'
  WHEN POSITION('Access denied. You do not have USAGE privilege on the engine.' in outcomeReason) > 0 THEN 'U|Access denied. You do not have USAGE privilege on the engine.'
  WHEN POSITION('Access denied. You do not have USAGE privilege on the project.' in outcomeReason) > 0 THEN 'U|Access denied. You do not have USAGE privilege on the project.'
  WHEN POSITION('Failure finding function:' in outcomeReason) > 0 THEN 'U|Failure finding function: <function signature>'
  WHEN POSITION('java.net.UnknownHostException' in outcomeReason) > 0 THEN 'U|UnknownHostException'
  WHEN POSITION('Caused By (java.net.UnknownHostException)' in outcomeReason) > 0 THEN 'U|UnknownHostException'
  WHEN POSITION('A table with the given name already exists' in outcomeReason) > 0 THEN 'U|Already exists'
  WHEN POSITION('already exists in schema' in outcomeReason) > 0 THEN 'U|Already exists'
  WHEN POSITION('Access denied reading dataset' in outcomeReason) > 0 THEN 'U|Access denied reading dataset'
  WHEN POSITION('AccessControlException:' in outcomeReason) > 0 THEN 'U|AccessControlException'
  WHEN POSITION('AccessControlException:' in outcomeReason) > 0 THEN 'U|AccessControlException'
  WHEN POSITION('Aggregate expression is illegal in GROUP BY clause' in outcomeReason) > 0 THEN 'U|Aggregate expression error'
  WHEN POSITION('Aggregate expression is illegal in WHERE clause' in outcomeReason) > 0 THEN 'U|Aggregate expression error'
  WHEN POSITION('Aggregate expression is illegal in ORDER BY clause of non-aggregating SELECT' in outcomeReason) > 0 THEN 'U|Aggregate expression error'
  WHEN POSITION('Aggregate expressions cannot be nested' in outcomeReason) > 0 THEN 'U|Aggregate expression error'
  WHEN POSITION('All arguments of call to macro' in outcomeReason) > 0 THEN 'U|All arguments of call to macro should be literal'
  WHEN POSITION('AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403;' in outcomeReason) > 0 THEN 'U|AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403;'
  WHEN POSITION('(com.amazonaws.services.s3.model.AmazonS3Exception) Access Denied (Service: Amazon S3; Status Code: 403;' in outcomeReason) > 0 THEN 'U|AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403;'
  WHEN POSITION('Access denied on s3://' in outcomeReason) > 0 THEN 'U|Access denied on s3://<path>'
  WHEN POSITION('because no identity-based policy allows the kms:GenerateDataKey action' in outcomeReason) > 0 THEN 'U|User is not authorized to perform kms:GenerateDataKey on resource'
  WHEN POSITION('AmazonS3Exception: The specified bucket does not exist' in outcomeReason) > 0 THEN 'U|AmazonS3Exception: The specified bucket does not exist'
  WHEN POSITION('AmazonS3Exception: Forbidden (' in outcomeReason) > 0 THEN 'U|AmazonS3Exception: Forbidden (403)'
  WHEN POSITION('AmazonS3Exception) The ciphertext refers to a customer master key' in outcomeReason) > 0 THEN 'U|AmazonS3Exception: The ciphertext refers to a customer master key that does not exist'
  WHEN POSITION('is not authorized to perform' in outcomeReason) > 0 THEN 'U|AmazonS3Exception: User is not authorized to perform <action> on resource'
  WHEN POSITION('Argument to function ''' in outcomeReason) > 0 THEN 'U|Argument to function must be a literal'
  WHEN POSITION('ARRAY_AGG currently does not support ordering within group' in outcomeReason) > 0 THEN 'U|ARRAY_AGG does not support ...'
  WHEN POSITION('ARRAY_AGG is not supported for NULL' in outcomeReason) > 0 THEN 'U|ARRAY_AGG does not support ...'
  WHEN POSITION('Invalid number of arguments to function' in outcomeReason) > 0 THEN 'U|Invalid number of arguments to function'
  WHEN POSITION('columns including leaf level fields of complex type are allowed to be scanned' in outcomeReason) > 0 THEN 'L|At most N columns including leaf level fields of complex type are allowed to be scanned'
  WHEN POSITION(' no longer active. Cancelling fragment ' in outcomeReason) > 0 THEN '?|AttemptManager <host> no longer active. Cancelling fragment <f>'
  WHEN POSITION('BETWEEN operator has no terminating AND' in outcomeReason) > 0 THEN 'U|BETWEEN operator has no terminating AND'
  WHEN POSITION('CONVERT_FROM does not support conversion from type' in outcomeReason) > 0 THEN 'U|CONVERT_FROM does not support conversion from type T'
  WHEN POSITION('Cannot apply = to the two different charsets' in outcomeReason) > 0 THEN 'U|Cannot apply = to the two different charsets C1 and C2'
  WHEN POSITION('Supported form(s)' in outcomeReason) > 0 THEN 'U|Cannot apply X to arguments of type'
  WHEN POSITION('since it has child tables' in outcomeReason) > 0 THEN 'L|Cannot drop table T since it has child tables'
  WHEN POSITION('Cannot create view in' in outcomeReason) > 0 THEN '?|Cannot create view in X'
  WHEN POSITION('does not support create view' in outcomeReason) > 0 THEN 'U|Source does not support view operations'
  WHEN POSITION('does not support update view' in outcomeReason) > 0 THEN 'U|Source does not support view operations'
  WHEN POSITION('does not support view operations' in outcomeReason) > 0 THEN 'U|Source does not support view operations'
  WHEN POSITION('Cannot assign to target field' in outcomeReason) > 0 THEN '?|Cannot assign to target field F1 of type T1 from source field F2 of type T2'
  WHEN POSITION('Cannot convert RexNode to equivalent Dremio expression' in outcomeReason) > 0 THEN '?|Cannot convert RexNode to equivalent Dremio expression'
  WHEN POSITION('while it is set in the current session''s reference context' in outcomeReason) > 0 THEN 'U|Cannot drop branch/tag X for source S while it is set in the current session''s reference context'
  WHEN POSITION('Cannot find table to create view from' in outcomeReason) > 0 THEN 'U|Cannot find table to create view from'
  WHEN POSITION('does not accept the supplied operand types: ' in outcomeReason) > 0 THEN 'U|FUNCTION does not accept the supplied operand types'
  WHEN POSITION('Cast function cannot convert value of type' in outcomeReason) > 0 THEN 'U|Cast function cannot convert value of type T1 to type T2'
  WHEN POSITION('Cannot infer type of field' in outcomeReason) > 0 THEN '?|Cannot infer type of field F within ROW type'
  WHEN POSITION('Cannot change data type of column' in outcomeReason) > 0 THEN 'U|Cannot change data type of column C from T1 to T2'
  WHEN POSITION('Cannot specify condition (NATURAL keyword, or ON or USING clause) following CROSS JOIN' in outcomeReason) > 0 THEN 'U|Cannot specify condition (NATURAL keyword, or ON or USING clause) following CROSS JOIN'
  WHEN POSITION('cannot translate call' in outcomeReason) > 0 THEN 'D|cannot translate call'
  WHEN POSITION('Change in Hive partition definition detected for table' in outcomeReason) > 0 THEN '?|Change in Hive partition definition detected for table T, re-promote the table to update the partition definition.'
  WHEN POSITION('Changing advanced system settings is not supported on Dremio Cloud.' in outcomeReason) > 0 THEN 'U|Changing advanced system settings is not supported on Dremio Cloud.'
  WHEN POSITION('ChannelClosedException: [USER]: Channel closed' in outcomeReason) > 0 THEN '?|ChannelClosedException: [USER]'
  WHEN POSITION('ChannelClosedException: [FABRIC]: Channel closed null <--> null (fabric client)' in outcomeReason) > 0 THEN '?|ChannelClosedException: [FABRIC]'
  WHEN POSITION('ChannelClosedException: [FABRIC]: Channel closed' in outcomeReason) > 0 THEN '?|ChannelClosedException'
  WHEN POSITION(''' not found in any table' in outcomeReason) > 0 THEN 'U|Column C not found in [any] table'
  WHEN POSITION(''' not found in table ''' in outcomeReason) > 0 THEN 'U|Column C not found in [any] table'
  WHEN POSITION('Column count mismatch in ' in outcomeReason) > 0 THEN 'U|Column count mismatch in UNION [ALL] | EXCEPT'
  WHEN POSITION(''' is ambiguous' in outcomeReason) > 0 THEN 'U|Column C is ambiguous'
  WHEN POSITION('] already in the table.' in outcomeReason) > 0 THEN 'U|Column C already in the table.'
  WHEN POSITION('is not present in table' in outcomeReason) > 0 THEN 'U|Column C is not present in table T'
  WHEN POSITION('Column has duplicate column name' in outcomeReason) > 0 THEN 'U|Duplicate column/relation name'
  WHEN POSITION('clause is not unique on one side of join' in outcomeReason) > 0 THEN 'U|Column name ... is not unique on one side of join'
  WHEN POSITION('specified multiple times.' in outcomeReason) > 0 THEN 'U|Column [<column>] specified multiple times'
  WHEN POSITION('Columns/Fields not specified for table.' in outcomeReason) > 0 THEN 'U|Columns/Fields not specified for table'
  WHEN POSITION(': error: too many constants' in outcomeReason) > 0 THEN 'D|CompileException: too many constants'
  WHEN POSITION(': error: code too large' in outcomeReason) > 0 THEN 'D|CompileException: code too large'
  WHEN POSITION('CommitFailedException) Version ' in outcomeReason) > 0 THEN '?|CommitFailedException: Version X already exists: <file>'
  WHEN POSITION('CommitFailedException: Table metadata refresh is required' in outcomeReason) > 0 THEN '?|CommitFailedException: Table metadata refresh is required'
  WHEN POSITION('CompileException) Compilation failed' in outcomeReason) > 0 THEN 'D|CompileException: Compilation failed'
  WHEN POSITION('Commit log is empty' in outcomeReason) > 0 THEN '?|Commit log is empty'
  WHEN POSITION('CompileException: Line' in outcomeReason) > 0 THEN '?|CompileException: Line X, Column Y'
  WHEN POSITION('ConcurrentModificationException: Document with' in outcomeReason) > 0 THEN '?|CME: Document with _id <id> (version <v>) already modified. You cannot save it now.'
  WHEN POSITION('ConcurrentModificationException: tried to update version' in outcomeReason) > 0 THEN '?|CME: tried to update version v1, found previous version v2'
  WHEN POSITION('ABORTED: Tag mismatch when updating dataset.' in outcomeReason) > 0 THEN '?|CME: Tag mismatch when updating dataset'
  WHEN POSITION('Concurrent DML operation has updated the table, please retry.' in outcomeReason) > 0 THEN 'U|CME: Concurrent DML operation has updated the table'
  WHEN POSITION('ABORTED: Tried to update a dataset that does not exist' in outcomeReason) > 0 THEN '?|CME: Tried to update a dataset that does not exist'
  WHEN POSITION('was updated, and the given configuration has older ctime' in outcomeReason) > 0 THEN '?|CME: Source [<source>] was updated, and the given configuration has older ctime'
  WHEN POSITION('Unable to refresh metadata for the dataset (due to concurrent updates). Please retry.' in outcomeReason) > 0 THEN 'U|CME: Unable to refresh metadata for the dataset (due to concurrent updates). Please retry.'
  WHEN POSITION('Unable to get task leader while trying to get ' in outcomeReason) > 0 THEN '?|Unable to get task leader while trying to get function/statistics/reflection information'
  WHEN POSITION('CONNECTION ERROR: Connection null <--> null (user client) closed unexpectedly. SabotNode down?' in outcomeReason) > 0 THEN '?|CONNECTION ERROR: Connection null <--> null (user client) closed unexpectedly. SabotNode down?'
  WHEN POSITION('ConnectException: Connection refused (Connection refused)' in outcomeReason) > 0 THEN '?|ConnectException: Connection refused'
  WHEN POSITION('ConnectException: finishConnect(..) failed: Connection refused' in outcomeReason) > 0 THEN '?|ConnectException: Connection refused'
  WHEN POSITION('A constant expression was encountered in the ORDER BY list' in outcomeReason) > 0 THEN 'U|A constant expression was encountered in the ORDER BY list'
  WHEN POSITION('Caused By (java.net.ConnectException) Connection refused' in outcomeReason) > 0 THEN '?|ConnectException: Connection refused'
  WHEN POSITION('Could not load value for key s3' in outcomeReason) > 0 THEN '?|Could not load value for key s3://<path>'
  WHEN POSITION('Could not send message to executor node for tag' in outcomeReason) > 0 THEN '?|Could not send message to executor node for tag T'
  WHEN POSITION('Create User failed: Setting password here is not allowed. Please set the password via the invite link in the email.' in outcomeReason) > 0 THEN 'U|Create User failed: Setting password here is not allowed'
  WHEN POSITION('Creating buckets is not supported' in outcomeReason) > 0 THEN 'U|Creating buckets is not supported'
  WHEN POSITION('Currently Very large case statements cannot have Gandiva only functions' in outcomeReason) > 0 THEN 'D|Currently Very large case statements cannot have Gandiva only functions'
  WHEN POSITION('(com.dremio.datastore.DatastoreException) Failed to get from store id' in outcomeReason) > 0 THEN '?|DatastoreException: Failed to get from store id'
  WHEN POSITION('does not exist or is not a table' in outcomeReason) > 0 THEN 'U|Dataset D does not exist or is not a table'
  WHEN POSITION('CTAS query cancelled because it will generate more than the limit of' in outcomeReason) > 0 THEN 'L|CTAS query cancelled because it will generate more than the limit of N partitions'
  WHEN POSITION('This version of the table ' in outcomeReason) > 0 THEN 'U|This version of the table [<table> is not available'
  WHEN POSITION('DATA_READ ERROR: With retry attempt failed to list files of directory' in outcomeReason) > 0 THEN '?|DATA_READ ERROR: With retry attempt failed to list files of directory D'
  WHEN POSITION('(java.lang.IllegalStateException) All the directories should have = in the partition structure' in outcomeReason) > 0 THEN 'U|All the directories should have = in the partition structure (IllegalStateException)'
  WHEN POSITION(') Error while streaming resultSet data
    org.mariadb.jdbc.export.ExceptionFactory.createException()' in outcomeReason) > 0 THEN '?|java.sql.SQLNonTransientConnectionException: Error while streaming resultSet data (mariadb)'
  WHEN POSITION(') Query execution was interrupted
    org.mariadb.jdbc.export.ExceptionFactory.createException()' in outcomeReason) > 0 THEN '?|java.sql.SQLTimeoutException: Query execution was interrupted (mariadb)'
  WHEN POSITION('(com.amazon.redshift.util.RedshiftException) ERROR: could not open relation with' in outcomeReason) > 0 THEN '?|RedshiftException: could not open relation with OID'
  WHEN POSITION('(org.postgresql.util.PSQLException) ERROR: canceling statement due to user request' in outcomeReason) > 0 THEN '?|PSQLException: canceling statement due to user request'
  WHEN POSITION('(net.snowflake.client.jdbc.SnowflakeSQLLoggedException) JDBC driver internal error' in outcomeReason) > 0 THEN '?|SnowflakeSQLLoggedException: JDBC driver internal error'
  WHEN POSITION('(java.sql.SQLException) ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit' in outcomeReason) > 0 THEN '?|ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit'
  WHEN POSITION('(org.postgresql.util.PSQLException) An I/O error occurred while sending to the backend' in outcomeReason) > 0 THEN '?|PSQLException: An I/O error occurred while sending to the backend'
  WHEN POSITION('communication buffer resources with another process and has been chosen as the deadlock victim' in outcomeReason) > 0 THEN '?|SQLServerException: Transaction (Process ID X) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim'
  WHEN POSITION(' is not supported on this' in outcomeReason) > 0 THEN 'U|<COMMAND> is not supported on this VIEW/SYSTEM_TABLE'
  WHEN POSITION('DISTINCT for window aggregate functions is not currently supported' in outcomeReason) > 0 THEN 'U|DISTINCT for window aggregate functions is not currently supported'
  WHEN POSITION('DatasetNotFoundException: Missing version' in outcomeReason) > 0 THEN '?|DatasetNotFoundException'
  WHEN POSITION('DatasetVersionNotFoundException: dataset' in outcomeReason) > 0 THEN '?|DatasetVersionNotFoundException'
  WHEN POSITION('Dremio does not currently support order by with ordinals in over clause' in outcomeReason) > 0 THEN 'U|Dremio does not currently support order by with ordinals in over clause'
  WHEN POSITION('Dremio doesn''t support using FLATTEN within DISTINCT' in outcomeReason) > 0 THEN 'U|Dremio doesn''t support using FLATTEN within DISTINCT'
  WHEN POSITION('Dremio only supports single statement execution' in outcomeReason) > 0 THEN 'U|Dremio only supports single statement execution. Unable to execute the given query with N statements'
  WHEN POSITION('Duplicate column name' in outcomeReason) > 0 THEN 'U|Duplicate column/relation name'
  WHEN POSITION('Duplicate relation name' in outcomeReason) > 0 THEN 'U|Duplicate column/relation name'
  WHEN POSITION('EOFException) Reached the end of stream with' in outcomeReason) > 0 THEN '?|EOFException: Reached the end of stream with X bytes left to read'
  WHEN POSITION('Error during planning the query.' in outcomeReason) > 0 THEN '?|Error during planning the query'
  WHEN POSITION('Error setting up remote fragment execution' in outcomeReason) > 0 THEN 'D|Error setting up remote fragment execution'
  WHEN POSITION('Caused By (java.lang.IllegalStateException) Received data batch for' in outcomeReason) > 0 THEN 'D|IllegalStateException: Received data batch for X from Y before fragment executor started'
  WHEN POSITION('Error while applying rule' in outcomeReason) > 0 THEN '?|Error while applying rule'
  WHEN POSITION('while waiting after sending work fragments to remote nodes. Sent' in outcomeReason) > 0 THEN '?|Exceeded timeout (N) while waiting after sending work fragments to remote nodes'
  WHEN POSITION('One or more result batches failed with ack timeout' in outcomeReason) > 0 THEN '?|One or more result batches failed with ack timeout'
  WHEN POSITION('Timed out while waiting for job results request response' in outcomeReason) > 0 THEN '?|Timed out while waiting for job results request response'
  WHEN POSITION('ExecutionSetupException: One or more nodes lost connectivity during query.' in outcomeReason) > 0 THEN '?|One or more nodes lost connectivity during query (ExecutionSetupException)'
  WHEN POSITION('Expected a boolean type' in outcomeReason) > 0 THEN 'U|Expected a boolean type'
  WHEN POSITION('Expected query or join' in outcomeReason) > 0 THEN 'U|Expected query or join'
  WHEN POSITION(''' is not being grouped' in outcomeReason) > 0 THEN 'U|Expression E is not being grouped'
  WHEN POSITION('FORGET METADATA is not supported on tables in homespace, sys, or INFORMATION_SCHEMA.' in outcomeReason) > 0 THEN 'U|FORGET METADATA is not supported on tables in homespace, sys, or INFORMATION_SCHEMA.'
  WHEN POSITION(''' is not in the select clause' in outcomeReason) > 0 THEN 'U|Expression E is not in the select clause'
  WHEN POSITION('Failed to build reflections on top of view/table with access controls' in outcomeReason) > 0 THEN 'U|Failed to build reflections on top of view/table with access controls'
  WHEN POSITION('Failed to check run query access privileges' in outcomeReason) > 0 THEN '?|Failed to check run query access privileges'
  WHEN POSITION('Failed to create new input stream for file:' in outcomeReason) > 0 THEN '?|Failed to create new input stream for file'
  WHEN POSITION('ERROR Failure to create directory' in outcomeReason) > 0 THEN '?|Failure to create directory'
  WHEN POSITION('MultiObjectDeleteException: One or more objects could not be deleted' in outcomeReason) > 0 THEN 'U|MultiObjectDeleteException: One or more objects could not be deleted'
  WHEN POSITION('Failed to find row access policy,' in outcomeReason) > 0 THEN 'U|Failed to find row access policy'
  WHEN POSITION('Failed to get iceberg metadata:' in outcomeReason) > 0 THEN '?|Failed to get iceberg metadata'
  WHEN POSITION('Failed to load the Iceberg table. Please make sure to use correct Iceberg catalog' in outcomeReason) > 0 THEN '?|Failed to load the Iceberg table'
  WHEN POSITION('Failed to load the Iceberg table. The underlying metadata and/or data files may not exist' in outcomeReason) > 0 THEN '?|Failed to load the Iceberg table'
  WHEN POSITION('org.apache.hadoop.hdfs.server.namenode.SafeModeException' in outcomeReason) > 0 THEN 'U|org.apache.hadoop.hdfs.server.namenode.SafeModeException: Name node is in safe mode.'
  WHEN POSITION('Failed to open input stream for file:' in outcomeReason) > 0 THEN '?|Failed to open stream for file'
  WHEN POSITION('Failed to open a new stream for file :' in outcomeReason) > 0 THEN '?|Failed to open stream for file'
  WHEN POSITION('Failed to read metadata for delta dataset' in outcomeReason) > 0 THEN '?|Failed to read metadata for delta dataset <path>'
  WHEN POSITION('Failure creating parser for entry' in outcomeReason) > 0 THEN '?|Failure creating parser for entry'
  WHEN POSITION('Unable to build AWSGlueClient: com.amazonaws.SdkClientException: Error while loading partitions file from com/amazonaws/partitions/endpoints.json' in outcomeReason) > 0 THEN '?|Unable to build AWSGlueClient: com.amazonaws.SdkClientException: Error while loading partitions file from com/amazonaws/partitions/endpoints.json'
  WHEN POSITION('was updated, and the given configuration has older version' in outcomeReason) > 0 THEN '?|ConcurrentModificationException: Source [S] was updated, and the given configuration has older version '
  WHEN POSITION('Failure getting source [redshift].' in outcomeReason) > 0 THEN 'U|Failure getting source [redshift] (ThoughtSpot POC)'
  WHEN POSITION('(java.lang.IllegalStateException) Current and given configurations for source' in outcomeReason) > 0 THEN 'D|Failure getting source (Current and given configurations for source [<source>] have same version (<version>) but different values)'
  WHEN POSITION('Failure to check if table already exists at path' in outcomeReason) > 0 THEN '?|Failure to check if table already exists at path P'
  WHEN POSITION('Failure while attempting to cast value ' in outcomeReason) > 0 THEN 'U|Failure while attempting to cast value ''V'' to T'
  WHEN POSITION('Failure while trying to parse JSON literal.' in outcomeReason) > 0 THEN '?|Failure while trying to parse JSON literal'
  WHEN POSITION('Error parsing JSON' in outcomeReason) > 0 THEN '?|Error parsing JSON'
  WHEN POSITION('Failure reading JSON file' in outcomeReason) > 0 THEN '?|Error parsing JSON'
  WHEN POSITION('Failure while parsing JSON' in outcomeReason) > 0 THEN '?|Error parsing JSON'
  WHEN POSITION('The top level of your document must either be a single array' in outcomeReason) > 0 THEN 'U|The top level of your document must either be a single array of maps or a set of white space delimited maps'
  WHEN POSITION(' exceeds the size limit of ' in outcomeReason) > 0 THEN 'L|Field F exceeds the size limit of N'
  WHEN POSITION('has incompatible types in file and table' in outcomeReason) > 0 THEN 'U|Field [F] has incompatible types in file and table.'
  WHEN POSITION('File format could not be inferred from the file extension, please specify FILE_FORMAT option.' in outcomeReason) > 0 THEN 'U|File format could not be inferred from the file extension'
  WHEN POSITION('exceeds maximum size limit for' in outcomeReason) > 0 THEN 'L|File exceeds maximum size limit for Excel files'
  WHEN POSITION('Caused By (java.io.FileNotFoundException) Version of file changed' in outcomeReason) > 0 THEN '?|FileNotFoundException: Version of file changed (S3AsyncByteReader)'
  WHEN POSITION('FileNotFoundException: File not found metadata/' in outcomeReason) > 0 THEN '?|FileNotFoundException: File not found metadata/<path>'
  WHEN POSITION('Caused By (java.io.FileNotFoundException) File not found' in outcomeReason) > 0 THEN '?|FileNotFoundException: File not found <path>'
  WHEN POSITION('Found unsupported partition listing in the table' in outcomeReason) > 0 THEN 'U|Found unsupported partition listing in the table [T]'
  WHEN POSITION('Folder already exists at path:' in outcomeReason) > 0 THEN 'U|Folder already exists at path'
  WHEN POSITION(''' is not empty' in outcomeReason) > 0 THEN 'U|Folder F is not empty'
  WHEN POSITION('FORBIDDEN (HTTP/403): Failed Access Check (HTTP/403): Read entity value is not allowed on reference' in outcomeReason) > 0 THEN 'U|FORBIDDEN (HTTP/403): Failed Access Check (HTTP/403): Read entity value is not allowed ...'
  WHEN POSITION('Found conflicting files that can contain records matching' in outcomeReason) > 0 THEN '?|Found conflicting files that can contain records matching ...'
  WHEN POSITION('can only be used in MATCH_RECOGNIZE' in outcomeReason) > 0 THEN 'U|Function F can only be used in MATCH_RECOGNIZE'
  WHEN POSITION('Function LAG only supports' in outcomeReason) > 0 THEN 'U|Function LAG only supports (<value expression>) or (<value expression>, 1)'
  WHEN POSITION('FUNCTION ERROR: Cannot parse ' in outcomeReason) > 0 THEN 'U|FUNCTION ERROR: Cannot parse '
  WHEN POSITION('FUNCTION ERROR: Failure parsing the formatting string' in outcomeReason) > 0 THEN 'U|FUNCTION ERROR: Failure parsing the formatting string'
  WHEN POSITION('FUNCTION ERROR: Illegal indexType' in outcomeReason) > 0 THEN 'U|FUNCTION ERROR: Illegal indexType ''I'''
  WHEN POSITION('FUNCTION ERROR: Unknown time-zone ID' in outcomeReason) > 0 THEN 'U|FUNCTION ERROR: Unknown time-zone ID: T'
  WHEN POSITION('FUNCTION ERROR: Unknown list element type' in outcomeReason) > 0 THEN 'U|FUNCTION ERROR: Unknown list element type'
  WHEN POSITION('(org.apache.arrow.gandiva.exceptions.UnsupportedTypeException) Unsupported type List' in outcomeReason) > 0 THEN '?|UnsupportedTypeException: Unsupported type List (Gandiva)'
  WHEN POSITION('GandivaException: Invalid millis for timestamp value' in outcomeReason) > 0 THEN 'U|Invalid datetime/timestamp conversion (Gandiva)'
  WHEN POSITION('GandivaException: Error parsing value' in outcomeReason) > 0 THEN 'U|Invalid datetime/timestamp conversion (Gandiva)'
  WHEN POSITION('GandivaException: Empty string cannot be converted to decimal128' in outcomeReason) > 0 THEN 'U|Invalid type conversion (Gandiva) '
  WHEN POSITION('GandivaException: Could not allocate memory for output string' in outcomeReason) > 0 THEN 'D|Could not allocate memory for output string (Gandiva)'
  WHEN POSITION('GandivaException: Index in split_part must be positive, value provided was' in outcomeReason) > 0 THEN 'U|Index in split_part must be positive, value provided was X (Gandiva)'
  WHEN POSITION('GandivaException: divide by zero error' in outcomeReason) > 0 THEN 'U|Divide by zero error (Gandiva)'
  WHEN POSITION('GandivaException: Failed to cast the string ' in outcomeReason) > 0 THEN 'U|Invalid type conversion (Gandiva) '
  WHEN POSITION('GandivaException: Not a valid date value' in outcomeReason) > 0 THEN 'U|Invalid datetime/timestamp conversion (Gandiva)'
  WHEN POSITION('GandivaException: Not a valid day for timestamp value' in outcomeReason) > 0 THEN 'U|Invalid datetime/timestamp conversion (Gandiva)'
  WHEN POSITION('GandivaException: Invalid timestamp or unknown zone for timestamp value' in outcomeReason) > 0 THEN 'U|Invalid datetime/timestamp conversion (Gandiva)'
  WHEN POSITION(' is not a valid decimal128 number' in outcomeReason) > 0 THEN 'U|The string ''<value>'' is not a valid decimal128 number (Gandiva)'
  WHEN POSITION('(org.apache.arrow.gandiva.exceptions.GandivaException) unexpected byte ' in outcomeReason) > 0 THEN 'U|Unexpected byte \xx encountered while decoding utf8 string (Gandiva)'
  WHEN POSITION('(org.apache.arrow.gandiva.exceptions.GandivaException) Buffer overflow for output string' in outcomeReason) > 0 THEN 'U|Buffer overflow for output string (Gandiva)'
  WHEN POSITION('Grant failed. Failed to grant privileges.' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed. OWNERSHIP is not a valid privilege for project.' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed. SELECT privilege is not supported' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant on all datasets under catalog entity failed, could not find' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Modifying privileges is not supported on' in outcomeReason) > 0 THEN 'U|Modifying privileges is not supported on <T>'
  WHEN POSITION('Granting or revoking source-level privileges is not supported on source' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed. INVALID_ARGUMENT:' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed. NOT_FOUND:' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed: Entity not found.' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed, role' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed. User' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant on catalog entity failed: No enum constant' in outcomeReason) > 0 THEN 'D|Grant on catalog entity failed: No enum constant CONSTANT'
  WHEN POSITION('Grant on catalog entity failed: INVALID_ARGUMENT: Invalid entity type.' in outcomeReason) > 0 THEN 'U|Grant on catalog entity failed'
  WHEN POSITION('Grant on catalog entity failed: Role' in outcomeReason) > 0 THEN 'U|Grant on catalog entity failed'
  WHEN POSITION('Grant on catalog entity failed, could not find' in outcomeReason) > 0 THEN 'U|Grant on catalog entity failed'
  WHEN POSITION('Grant on catalog entity failed' in outcomeReason) > 0 THEN 'U|Grant on catalog entity failed'
  WHEN POSITION('HAVING clause must be a condition' in outcomeReason) > 0 THEN 'U|HAVING/ON/WHERE clause must be a condition'
  WHEN POSITION('Hive views are not supported' in outcomeReason) > 0 THEN 'U|Hive views are not supported'
  WHEN POSITION('replace string must be 0 or 1 characters long' in outcomeReason) > 0 THEN 'U|In convert_from(<input>, ''UTF8'', <replace string>), replace string must be 0 or 1 characters long'
  WHEN POSITION('INNER, LEFT, RIGHT or FULL join requires a condition (NATURAL keyword or ON or USING clause)' in outcomeReason) > 0 THEN 'U|INNER, LEFT, RIGHT or FULL join requires a condition'
  WHEN POSITION('INTERNAL: state should be: server session pool is open' in outcomeReason) > 0 THEN '?|INTERNAL: state should be: server session pool is open'
  WHEN POSITION('IOException: Not a file' in outcomeReason) > 0 THEN '?|IOException: Not a file: <path>'
  WHEN POSITION('IOException: No space left on device' in outcomeReason) > 0 THEN '?|IOException: No space left on device'
  WHEN POSITION('is not a Parquet file. expected magic number [80, 65, 82, 49] at tail, but found' in outcomeReason) > 0 THEN '?|IOException) <path> is not a Parquet file. expected magic number [80, 65, 82, 49] at tail, but found [x, x, x, x]'
  WHEN POSITION('Caused By (com.dremio.io.AsyncByteReaderWithTimeout.AsyncTimeoutException) null
    com.dremio.io.AsyncByteReaderWithTimeout.lambda$within$1()' in outcomeReason) > 0 THEN '?|AsyncTimeoutException (via AsyncByteReaderWithTimeout)'
  WHEN POSITION(': FileSystem is closed!' in outcomeReason) > 0 THEN 'D|IOException: <bucket>: FileSystem is closed!'
  WHEN POSITION('Iceberg metadata function (''table_history'') is not supported on table' in outcomeReason) > 0 THEN 'U|Iceberg metadata function F not supported on table'
  WHEN POSITION('Iceberg metadata function' in outcomeReason) > 0 THEN 'U|Iceberg metadata function F not supported on table'
  WHEN POSITION('] not authorized to' in outcomeReason) > 0 THEN 'U|Identity/User not authorized to OP'
  WHEN POSITION('] not authorized to' in outcomeReason) > 0 THEN 'U|Identity/User not authorized to OP'
  WHEN POSITION('] not authorized to' in outcomeReason) > 0 THEN 'U|Identity/User not authorized to OP'
  WHEN POSITION('] not authorized to' in outcomeReason) > 0 THEN 'U|Identity/User not authorized to OP'
  WHEN POSITION(': not in format' in outcomeReason) > 0 THEN 'U|Illegal DATE/TIMESTAMP literal X not in format Y'
  WHEN POSITION(': not in format' in outcomeReason) > 0 THEN 'U|Illegal DATE/TIMESTAMP literal X not in format Y'
  WHEN POSITION('Illegal mixing of types in CASE or COALESCE statement' in outcomeReason) > 0 THEN 'U|Illegal mixing of types in CASE or COALESCE statement'
  WHEN POSITION('Illegal use of dynamic parameter' in outcomeReason) > 0 THEN '?|Illegal use of dynamic parameter'
  WHEN POSITION('IllegalArgumentException: Could not find entity' in outcomeReason) > 0 THEN '?|IAE: Could not find entity'
  WHEN POSITION('IllegalArgumentException: Cannot add duplicate partition field' in outcomeReason) > 0 THEN 'U|IAE: Cannot add duplicate partition field'
  WHEN POSITION('com.dremio.exec.store.parquet.ParquetSplitCreator.createSplit()' in outcomeReason) > 0 THEN '?|IAE: null @ ParquetSplitCreator.createSplit()'
  WHEN POSITION('of type FOLDER. Please check the entity type specified.' in outcomeReason) > 0 THEN 'U|IAE: Could not find entity <entity> of type FOLDER.'
  WHEN POSITION('of type VDS. Please check the entity type specified.' in outcomeReason) > 0 THEN 'U|IAE: Could not find entity <entity> of type VDS.'
  WHEN POSITION('of type PDS. Please check the entity type specified.' in outcomeReason) > 0 THEN 'U|IAE: Could not find entity <entity> of type PDS.'
  WHEN POSITION('should have been either a varchar or varbinary' in outcomeReason) > 0 THEN 'U|IAE: Incoming field [''<field>''] should have been either a varchar or varbinary'
  WHEN POSITION('IllegalArgumentException) Multiple entries with same key' in outcomeReason) > 0 THEN '?|IAE: IllegalArgumentException) Multiple entries with same key'
  WHEN POSITION('IllegalArgumentException) Can not create a Path from an empty string' in outcomeReason) > 0 THEN '?|IAE: Can not create a Path from an empty string'
  WHEN POSITION('IllegalArgumentException) Invalid format: ' in outcomeReason) > 0 THEN 'U|IAE: Invalid format: ''<format>'' is malformed at ''<part>'''
  WHEN POSITION('IllegalArgumentException: Wrong FS' in outcomeReason) > 0 THEN '?|IAE: Wrong FS s3://foo/bar -expected s3://foo/'
  WHEN POSITION(' is not a Parquet file (too small)' in outcomeReason) > 0 THEN 'U|IAE: <file>is not a Parquet file (too small)'
  WHEN POSITION('IllegalArgumentException) The argument ''destTz'' of Function ''convert_timezone'' has to be constant!' in outcomeReason) > 0 THEN 'U|IAE: IllegalArgumentException) The argument ''destTz'' of Function ''convert_timezone'' has to be constant!'
  WHEN POSITION('IllegalArgumentException) The argument ''pattern'' of Function ''like'' has to be constant!' in outcomeReason) > 0 THEN 'U|IAE: The argument ''pattern'' of Function ''like'' has to be constant!'
  WHEN POSITION('IllegalStateException: Attempted to send a message when connection is no longer valid' in outcomeReason) > 0 THEN '?|IllegalStateException: Attempted to send a message when connection is no longer valid'
  WHEN POSITION('IllegalStateException: Connection pool shut down' in outcomeReason) > 0 THEN '?|IllegalStateException: Connection pool shut down'
  WHEN POSITION('Memory was leaked by query' in outcomeReason) > 0 THEN 'D|Memory was leaked by query'
  WHEN POSITION('IllegalStateException: Selected partition ' in outcomeReason) > 0 THEN '?|IllegalStateException: Selected partition '
  WHEN POSITION('IllegalStateException: Source is not mutable' in outcomeReason) > 0 THEN '?|IllegalStateException: Source is not mutable'
  WHEN POSITION('IllegalStateException: not enough buffers for field major_type' in outcomeReason) > 0 THEN '?|IllegalStateException: not enough buffers for field major_type'
  WHEN POSITION('is too large to fit into page size' in outcomeReason) > 0 THEN '?|IllegalStateException: Individual record size (x) is too large to fit into page size (y) (Memory)'

  WHEN POSITION('Dremio does not support casting or coercing' in outcomeReason) > 0 THEN 'U|Dremio does not support casting or coercing'
  WHEN POSITION('Input buffer segment is of invalid length' in outcomeReason) > 0 THEN '?|Input buffer segment is of invalid length'
  WHEN POSITION('Input text cannot be formatted to ' in outcomeReason) > 0 THEN 'U|Input text cannot be formatted to date/timestamp'
  WHEN POSITION('Compiling "new UnionListReader' in outcomeReason) > 0 THEN '?|InternalCompilerException: new UnionListReader'
  WHEN POSITION(' exceeds precision of DAY(2) field' in outcomeReason) > 0 THEN '?|Interval field value N exceeds precision of DAY(2) field'
  WHEN POSITION('Invalid column type' in outcomeReason) > 0 THEN 'U|Invalid column type'
  WHEN POSITION('Invalid formatting string' in outcomeReason) > 0 THEN 'U|Invalid formatting string'
  WHEN POSITION('Invalid ID for region-based ZoneId' in outcomeReason) > 0 THEN 'U|Invalid ID for region-based ZoneId'
  WHEN POSITION('Invalid name space key. Given:' in outcomeReason) > 0 THEN '?|Invalid name space key'
  WHEN POSITION('Invalid number of arguments to function' in outcomeReason) > 0 THEN '?|Invalid number of arguments to function F. Was expecting N arguments'
  WHEN POSITION('Invalid path. Given path,' in outcomeReason) > 0 THEN '?|Invalid path'
  WHEN POSITION('Invalid regex expression' in outcomeReason) > 0 THEN 'U|Invalid regex expression'
  WHEN POSITION('Invalid schema: multiple fields for name' in outcomeReason) > 0 THEN 'U|Invalid schema: multiple fields for name N'
  WHEN POSITION('cannot be both a sort and a partition' in outcomeReason) > 0 THEN 'U|Invalid reflection'
  WHEN POSITION('Invalid reflection: ' in outcomeReason) > 0 THEN '?|Invalid reflection'
  WHEN POSITION('Invalid value for boolean: ''' in outcomeReason) > 0 THEN 'U|Invalid value for boolean: ''V'' '
  WHEN POSITION('(com.fasterxml.jackson.core.JsonParseException) Unrecognized token' in outcomeReason) > 0 THEN 'U|JsonParseException: Unrecognized token'
  WHEN POSITION('(com.fasterxml.jackson.core.JsonParseException) Unexpected character' in outcomeReason) > 0 THEN 'U|JsonParseException: Unexpected character'
  WHEN POSITION('DATA_READ ERROR: Failure converting field' in outcomeReason) > 0 THEN '?|Failure converting field <field> from JSON'
  WHEN POSITION('Malformed CSV file: expected closing quote symbol for a quoted value' in outcomeReason) > 0 THEN 'U|UnmatchedQuoteException: Malformed CSV file'
  WHEN POSITION('(org.apache.arrow.vector.util.OversizedAllocationException) Memory required for vector is' in outcomeReason) > 0 THEN '?|OversizedAllocationException: Memory required for vector is (x), which is overflow or more than max allowed (y)'
  WHEN POSITION('Failed to create directory for spilling.' in outcomeReason) > 0 THEN '?|Failed to create directory for spilling'
  WHEN POSITION('JSON_FIELD_CHANGE ERROR: New field in the schema found.' in outcomeReason) > 0 THEN '?|JSON_FIELD_CHANGE ERROR: New field in the schema found'
  WHEN POSITION('Job was canceled because the query is too complex. Please simplify the query.' in outcomeReason) > 0 THEN 'L|Job was canceled because the query is too complex. Please simplify the query.'
  WHEN POSITION('has conflicting put-operation from commit ' in outcomeReason) > 0 THEN '?|Key <key> has conflicting put-operation from commit <commit>'
  WHEN POSITION('LAG, LEAD or NTILE functions require ORDER BY clause in window specification' in outcomeReason) > 0 THEN 'U|LAG, LEAD or NTILE functions require ORDER BY clause in window specification'
  WHEN POSITION('Left expression cannot be null.' in outcomeReason) > 0 THEN 'U|Left expression cannot be null'
  WHEN POSITION(' must be less than or equal to 1024 characters' in outcomeReason) > 0 THEN 'U|Length of identifier must be less than or equal to 1024 characters'
  WHEN POSITION('Lexical error at line ' in outcomeReason) > 0 THEN 'U|Lexical error at line X, column Y'
  WHEN POSITION('exceeded the maximum number of elements' in outcomeReason) > 0 THEN 'L|List field F exceeded the maximum number of elements N'
  WHEN POSITION('List of column aliases must have same degree as table' in outcomeReason) > 0 THEN 'U|List of column aliases must have same degree as table'
  WHEN POSITION('(java.nio.charset.MalformedInputException) Input length = 1' in outcomeReason) > 0 THEN 'D|MalformedInputException: Input length = 1'
  WHEN POSITION('Map support is ON. Reformat the dataset to read map columns as native maps or disable support key' in outcomeReason) > 0 THEN 'U|Map support is ON. Reformat the dataset to read map columns as native maps or disable support key'
  WHEN POSITION('Max Rel Metadata call count exceeded' in outcomeReason) > 0 THEN '?|Max Rel Metadata call count exceeded'
  WHEN POSITION('Materialization cancelled due to excessive partition creation' in outcomeReason) > 0 THEN 'L|Materialization cancelled due to excessive partition creation'
  WHEN POSITION('failed due to commit conflict on source' in outcomeReason) > 0 THEN 'U|Merge branch <B1> into branch <B2> failed due to commit conflict on source <S>'
  WHEN POSITION('failed due to missing branch on source' in outcomeReason) > 0 THEN 'U|Merge branch <B1> into branch <B2> failed due to missing branch on source <S>'
  WHEN POSITION('Insufficient Lake Formation permission' in outcomeReason) > 0 THEN '?|Insufficient Lake Formation permission(s)'
  WHEN POSITION('MongoSocketReadException: Prematurely reached end of stream' in outcomeReason) > 0 THEN '?|MongoSocketReadException: Prematurely reached end of stream'
  WHEN POSITION('MongoCursorNotFoundException: Command failed with error 43' in outcomeReason) > 0 THEN '?|MongoCursorNotFoundException: Command failed with error 43'
  WHEN POSITION('MongoCursorNotFoundException: Query failed with error code -5' in outcomeReason) > 0 THEN '?|MongoCursorNotFoundException: Query failed with error code -5'
  WHEN POSITION('MongoNodeIsRecoveringException: Command failed with error 11600' in outcomeReason) > 0 THEN '?|MongoNodeIsRecoveringException: Command failed with error 11600 (InterruptedAtShutdown)'
  WHEN POSITION('MongoQueryException: Command failed with error 11600 (InterruptedAtShutdown)' in outcomeReason) > 0 THEN '?|MongoNodeIsRecoveringException: Command failed with error 11600 (InterruptedAtShutdown)'
  WHEN POSITION('Command failed with error 13 (Unauthorized)' in outcomeReason) > 0 THEN '?|MongoQueryException: Command failed with error 13 (Unauthorized)'
  WHEN POSITION('com.mongodb.MongoTimeoutException: Timed out after' in outcomeReason) > 0 THEN '?|MongoTimeoutException: Timed out after X ms'
  WHEN POSITION('NamespaceNotFoundException: not found' in outcomeReason) > 0 THEN 'U|NamespaceNotFoundException'
  WHEN POSITION('NamespaceNotFoundException: Not found:' in outcomeReason) > 0 THEN 'U|NamespaceNotFoundException'
  WHEN POSITION('NamespaceNotFoundException: one or more elements on the path are not found in namespace' in outcomeReason) > 0 THEN 'U|NamespaceNotFoundException'
  WHEN POSITION('Native row-access and column-masking policies are not supported on' in outcomeReason) > 0 THEN 'U|Native row-access and column-masking policies are not supported'
  WHEN POSITION('NativeIoException: readAddress' in outcomeReason) > 0 THEN '?|NativeIoException: readAddress'
  WHEN POSITION('NessieBadRequestException:' in outcomeReason) > 0 THEN '?|NessieBadRequestException'
  WHEN POSITION('NessieReferenceConflictException' in outcomeReason) > 0 THEN '?|NessieReferenceConflictException'
  WHEN POSITION('No column name matches target schema' in outcomeReason) > 0 THEN 'U|No column name matches target schema'
  WHEN POSITION('No enum constant com.dremio.common.types.TypeProtos.MinorType.ROW' in outcomeReason) > 0 THEN '?|No enum constant com.dremio.common.types.TypeProtos.MinorType.ROW'
  WHEN POSITION('Caused By (org.apache.http.NoHttpResponseException) The target server failed to respond' in outcomeReason) > 0 THEN 'U|NoHttpResponseException: The target server failed to respond'
  WHEN POSITION('Unable to execute HTTP request: The target server failed to respond' in outcomeReason) > 0 THEN 'U|NoHttpResponseException: The target server failed to respond'
  WHEN POSITION('No match found for function signature' in outcomeReason) > 0 THEN 'U|No match found for function signature'
  WHEN POSITION('No permission to requested path.' in outcomeReason) > 0 THEN '?|No permission to requested path.'
  WHEN POSITION('(org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException) Credentials requested after provider list was closed' in outcomeReason) > 0 THEN '?|NoAuthWithAWSException: Credentials requested after provider list was closed'
  WHEN POSITION('HTTP connection failed for getting token from AzureAD. Http response: 401 Unauthorized' in outcomeReason) > 0 THEN 'U|HTTP connection failed for getting token from AzureAD (401 Unauthorized)'
  WHEN POSITION('NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy' in outcomeReason) > 0 THEN '?|NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy'
  WHEN POSITION('NoClassDefFoundError: Could not initialize class org.apache.hadoop.io.erasurecode.CodecRegistry' in outcomeReason) > 0 THEN '?|NoClassDefFoundError: Could not initialize class org.apache.hadoop.io.erasurecode.CodecRegistry'
  WHEN POSITION('NoNodeException: KeeperErrorCode = NoNode' in outcomeReason) > 0 THEN '?|NoNodeException: KeeperErrorCode = NoNode'
  WHEN POSITION('could not be implemented; planner state' in outcomeReason) > 0 THEN '?|Node N could not be implemented'
  WHEN POSITION('Non-query expression encountered in illegal context' in outcomeReason) > 0 THEN 'U|Non-query expression encountered in illegal context'
  WHEN POSITION('Not a record type.' in outcomeReason) > 0 THEN 'U|Not a record type. The ''*'' operator requires a record'
  WHEN POSITION('exceeds the query split limit of ' in outcomeReason) > 0 THEN 'L|Number of splits in the query (X) exceeds the query split limit of Y'
  WHEN POSITION('The operation is not valid for the object''s storage class' in outcomeReason) > 0 THEN 'U|AmazonS3Exception: The operation is not valid for the object''s storage class'
  WHEN POSITION('Caused By (org.apache.hadoop.hdfs.BlockMissingException) Could not obtain block' in outcomeReason) > 0 THEN 'U|org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block (No live nodes contain current block)'
  WHEN POSITION('Caused By (org.apache.hadoop.ipc.RemoteException) File does not exist: ' in outcomeReason) > 0 THEN 'U|org.apache.hadoop.ipc.RemoteException: File does not exist'
  WHEN POSITION('The condition specified using HTTP conditional header(s) is not met.' in outcomeReason) > 0 THEN 'U|AbfsRestOperationException: The condition specified using HTTP conditional header(s) is not met'
  WHEN POSITION('Caused By (java.io.EOFException) Attempted to seek or read past the end of the file' in outcomeReason) > 0 THEN '?|java.io.EOFException: Attempted to seek or read past the end of the file'
  WHEN POSITION('Caused By (org.apache.hadoop.fs.ChecksumException) Checksum error' in outcomeReason) > 0 THEN '?|org.apache.hadoop.fs.ChecksumException: Checksum error'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.parquet.pages.async.RowGroupReader.getStream()' in outcomeReason) > 0 THEN '?|NPE: RowGroupReader.getStream()'
  WHEN POSITION('com.dremio.exec.store.parquet2.ParquetRowiseReader.setup():325' in outcomeReason) > 0 THEN '?|NPE: RowGroupReader.getStream()'
  WHEN POSITION('(java.lang.NullPointerException) null
    org.apache.parquet.format.converter.ParquetMetadataConverter.getPath()' in outcomeReason) > 0 THEN 'D|NPE: ParquetMetadataConverter.getPath()'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.exec.store.dfs.SplitAssignmentTableFunction$ComparableEndpoint.access$300()' in outcomeReason) > 0 THEN '?|NPE: SplitAssignmentTableFunction$ComparableEndpoint.access$300()'
  WHEN POSITION('com.dremio.exec.store.iceberg.model.IncrementalMetadataRefreshCommitter.setTablePropertyToCleanOldMetadataFiles()' in outcomeReason) > 0 THEN '?|NPE: IncrementalMetadataRefreshCommitter.setTablePropertyToCleanOldMetadataFiles()'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.exec.store.parquet.ParquetRecordWriter.getTypeWithId()' in outcomeReason) > 0 THEN '?|NPE: ParquetRecordWriter.getTypeWithId()'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.exec.store.dfs.SplitAssignmentTableFunction.startRow()' in outcomeReason) > 0 THEN '?|NPE: SplitAssignmentTableFunction.startRow()'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.exec.vector.complex.fn.JsonReader' in outcomeReason) > 0 THEN '?|NPE: JsonReader'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.exec.store.iceberg.model.IncrementalMetadataRefreshCommitter.postCommitTransaction()' in outcomeReason) > 0 THEN '?|NPE: IncrementalMetadataRefreshCommitter'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.exec.store.parquet.UpPromotingParquetReader.setupMutator()' in outcomeReason) > 0 THEN '?|NPE: UpPromotingParquetReader.setupMutator()'
  WHEN POSITION('(java.lang.NullPointerException) null
    com.dremio.exec.store.iceberg.model.IncrementalMetadataRefreshCommitter.collectFilesForSnapshot()' in outcomeReason) > 0 THEN '?|NPE: IncrementalMetadataRefreshCommitter'
  WHEN POSITION('com.dremio.service.reflection.materialization.AccelerationStoragePlugin.sanitizePath()' in outcomeReason) > 0 THEN 'D|NPE: AccelerationStoragePlugin.sanitizePath()'
  WHEN POSITION('exceeds dataset split limit of' in outcomeReason) > 0 THEN 'L|Number of splits (N) in dataset D exceeds dataset split limit of X'
  WHEN POSITION('ON clause must be a condition' in outcomeReason) > 0 THEN 'U|HAVING/ON/WHERE clause must be a condition'
  WHEN POSITION('ORDER BY columns must be subset LISTAGG columns' in outcomeReason) > 0 THEN 'U|ORDER BY columns must be subset LISTAGG columns'
  WHEN POSITION('OVER clause is necessary for window functions' in outcomeReason) > 0 THEN 'U|OVER clause is necessary for window functions'
  WHEN POSITION('OVER must be applied to aggregate function' in outcomeReason) > 0 THEN 'U|OVER must be applied to aggregate function'
  WHEN POSITION('Please check that it exists in the selected context.' in outcomeReason) > 0 THEN 'U|Object not found. Please check that it exists in the selected context.'
  WHEN POSITION('One or more of the referred data files are absent' in outcomeReason) > 0 THEN '?|One or more of the referred data files are absent'
  WHEN POSITION('Only one data line detected. Please consider changing line delimiter.' in outcomeReason) > 0 THEN 'U|Only one data line detected'
  WHEN POSITION('Only tables can be refreshed. Dataset' in outcomeReason) > 0 THEN 'U|Only tables can be refreshed. Dataset <D> is a view'
  WHEN POSITION('Operand types mismatch for: ' in outcomeReason) > 0 THEN '?|Operand types mismatch for: F'
  WHEN POSITION('org.apache.iceberg.exceptions.NotFoundException: Path' in outcomeReason) > 0 THEN '?|org.apache.iceberg.exceptions.NotFoundException: Path'
  WHEN POSITION('ORDER BY unexpected' in outcomeReason) > 0 THEN 'U|ORDER BY unexpected'
  WHEN POSITION('Out of memory while receiving incoming message' in outcomeReason) > 0 THEN 'D|Out of memory while receiving incoming message'
  WHEN POSITION('Parameters must be of the same type' in outcomeReason) > 0 THEN 'U|Parameters must be of the same type'
  WHEN POSITION('SYSTEM ERROR: ParquetCompressionCodecException' in outcomeReason) > 0 THEN 'D|ParquetCompressionCodecException'
  WHEN POSITION('is not in the SELECT list of CTAS!' in outcomeReason) > 0 THEN 'U|Partition column C is not in the SELECT list of CTAS!'
  WHEN POSITION('are not found in table.' in outcomeReason) > 0 THEN 'U|Partition column(s) [C1, C2] are not found in table'
  WHEN POSITION('could not be resolved in the table''s column lists' in outcomeReason) > 0 THEN 'U|Partition column C could not be resolved in the table''s column lists'
  WHEN POSITION('Path @' in outcomeReason) > 0 THEN '?|Path @P not found'
  WHEN POSITION('ERROR: permission denied for schema ' in outcomeReason) > 0 THEN '?|Permission denied for schema S'
  WHEN POSITION('Prematurely reached end of stream' in outcomeReason) > 0 THEN '?|Prematurely reached end of stream'
  WHEN POSITION('Preview engine unavailable' in outcomeReason) > 0 THEN '?|Preview engine unavailable'
  WHEN POSITION('is not a known type. The supported list is:' in outcomeReason) > 0 THEN 'U|Provided type: T is not a known type. The supported list is ...'
  WHEN POSITION('Provider for class javax.xml.stream.XMLInputFactory cannot be created' in outcomeReason) > 0 THEN 'D|Provider for class javax.xml.stream.XMLInputFactory cannot be created'
  WHEN POSITION('ProtocolNotRegisteredException' in outcomeReason) > 0 THEN 'D|ProtocolNotRegisteredException'
  WHEN POSITION('QueryProfile did not have a serialized plan' in outcomeReason) > 0 THEN 'D|QueryProfile did not have a serialized plan'
  WHEN POSITION('Query cancelled by Workload Manager. Query runtime limit of' in outcomeReason) > 0 THEN 'L|Query runtime limit of N seconds exceeded (WLM)'
  WHEN POSITION('Query cancelled by Workload Manager. Query enqueued time of' in outcomeReason) > 0 THEN 'L|Query enqueued time of N seconds exceeded (WLM)'
  WHEN POSITION('The query was rejected based on the workload management (WLM) rule configuration' in outcomeReason) > 0 THEN 'L|The query was rejected based on the workload management (WLM) rule configuration'
  WHEN POSITION('Query failed as Dremio was restarted. Details and profile information for this job may be missing.' in outcomeReason) > 0 THEN 'L|Query failed as Dremio was restarted'
  WHEN POSITION('Query failed due to kvstore or network errors. Details and profile information for this job may be partial or missing.' in outcomeReason) > 0 THEN 'D|Query failed due to kvstore or network errors'
  WHEN POSITION('while waiting to be scheduled. The concurrency is higher than the value that is supported by the maxReplicas of the engine' in outcomeReason) > 0 THEN '?|Query timed out on the engine E while waiting to be scheduled'
  WHEN POSITION('Query was cancelled because it exceeded the memory limits set by the administrator' in outcomeReason) > 0 THEN 'L|Query was cancelled because it exceeded the memory limits set by the administrator'
  WHEN POSITION('Query was cancelled because planning time exceeded' in outcomeReason) > 0 THEN '?|Query was cancelled because planning time exceeded X seconds'
  WHEN POSITION(' did not start. No active engine replicas available' in outcomeReason) > 0 THEN 'U|Query was cancelled as the <engine> engine did not start. No active engine replicas available.'
  WHEN POSITION('PatternSyntaxException' in outcomeReason) > 0 THEN '?|PatternSyntaxException'
  WHEN POSITION('RANK or DENSE_RANK functions require ORDER BY clause in window specification' in outcomeReason) > 0 THEN 'U|RANK or DENSE_RANK functions require ORDER BY clause in window specification'
  WHEN POSITION('does not support operand types' in outcomeReason) > 0 THEN 'U|F does not support operand types'
  WHEN POSITION('Dremio doesn''t currently support' in outcomeReason) > 0 THEN 'U|Dremio doesn''t currently support ...'
  WHEN POSITION('Jaunt plugin doesn''t support' in outcomeReason) > 0 THEN 'U|Jaunt plugin doesn''t support'
  WHEN POSITION('The first argument of date_trunc function must be time units' in outcomeReason) > 0 THEN 'U|The first argument of date_trunc function must be time units'
  WHEN POSITION('extract function supports the following time units' in outcomeReason) > 0 THEN 'U|extract function supports the following time units ...'
  WHEN POSITION('Query cancelled by Reflection Manager. Reflection configuration is stale' in outcomeReason) > 0 THEN 'U|Query cancelled by Reflection Manager. Reflection configuration is stale'
  WHEN POSITION(' already exists in Source ' in outcomeReason) > 0 THEN 'U|Reference R already exists in Source S'
  WHEN POSITION('Requested commit ' in outcomeReason) > 0 THEN 'U|Requested commit C not found in source S'
  WHEN POSITION('Rejecting query because it exceeded the maximum allowed number of live queries in a single coordinator' in outcomeReason) > 0 THEN 'L|Rejecting query because it exceeded the maximum allowed number of live queries in a single coordinator'
  WHEN POSITION('ResourceAllocationException: Engine either does not exist or is disabled with name Big Engine' in outcomeReason) > 0 THEN '?|ResourceAllocationException: Engine either does not exist or is disabled with name N'
  WHEN POSITION('Resource not found at path @' in outcomeReason) > 0 THEN '?|Resource not found at path @...'
  WHEN POSITION('Revoke on catalog entity failed, could not find' in outcomeReason) > 0 THEN '?|Revoke on catalog entity failed'
  WHEN POSITION('S3 request failed on resource' in outcomeReason) > 0 THEN '?|S3 request failed on resource R'
  WHEN POSITION('is not valid with respect to either root schema or current default schema.' in outcomeReason) > 0 THEN '?|Schema S is not valid with respect to either root schema or current default schema.'
  WHEN POSITION('New schema found. Please reattempt the query' in outcomeReason) > 0 THEN '?|Schema change (New schema found)'
  WHEN POSITION('Schema change detected' in outcomeReason) > 0 THEN '?|Schema change (Schema change detected)'
  WHEN POSITION('SdkInterruptedException' in outcomeReason) > 0 THEN '?|SdkInterruptedException'
  WHEN POSITION('Selected table has no columns.' in outcomeReason) > 0 THEN '?|Selected table has no columns'
  WHEN POSITION('SetOwner could not find role or active user' in outcomeReason) > 0 THEN '?|SetOwner could not find role or active user ''<user>'' of type ''<type>'''
  WHEN POSITION('SocketException: Socket closed' in outcomeReason) > 0 THEN '?|SocketException: Socket closed'
  WHEN POSITION('Some virtual datasets are out of date and need to be manually updated.' in outcomeReason) > 0 THEN '?|Some virtual datasets are out of date and need to be manually updated.'
  WHEN POSITION('Sorting by arrays is not supported' in outcomeReason) > 0 THEN 'U|Sorting by arrays is not supported'
  WHEN POSITION('does not support versioning.' in outcomeReason) > 0 THEN '?|Source S does not support versioning.'
  WHEN POSITION('does not support AT BRANCH/TAG/COMMIT specification' in outcomeReason) > 0 THEN 'U|Source S does not support AT BRANCH/TAG/COMMIT specification'
  WHEN POSITION('] does not support this operation' in outcomeReason) > 0 THEN 'U|Source [<source>] does not support this operation (Iceverg)'
  WHEN POSITION('Specified location clause not found, Dremio sources should precede with' in outcomeReason) > 0 THEN '?|Specified location clause not found'
  WHEN POSITION('SslClosedEngineException: SSLEngine closed already' in outcomeReason) > 0 THEN 'D|SslClosedEngineException: SSLEngine closed already'
  WHEN POSITION('RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR' in outcomeReason) > 0 THEN '?|RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR'
  WHEN POSITION('StatusRuntimeException: DEADLINE_EXCEEDED' in outcomeReason) > 0 THEN '?|StatusRuntimeException: DEADLINE_EXCEEDED'
  WHEN POSITION('StatusRuntimeException: INTERNAL' in outcomeReason) > 0 THEN '?|StatusRuntimeException: INTERNAL'
  WHEN POSITION('StatusRuntimeException: INVALID_ARGUMENT' in outcomeReason) > 0 THEN '?|StatusRuntimeException: INVALID_ARGUMENT'
  WHEN POSITION('StatusRuntimeException: FAILED_PRECONDITION' in outcomeReason) > 0 THEN '?|StatusRuntimeException: FAILED_PRECONDITION'
  WHEN POSITION('StatusRuntimeException: UNAVAILABLE' in outcomeReason) > 0 THEN '?|StatusRuntimeException: UNAVAILABLE'
  WHEN POSITION('StatusRuntimeException: CANCELLED: RPC cancelled' in outcomeReason) > 0 THEN '?|StatusRuntimeException: CANCELLED: RPC cancelled
'
  WHEN POSITION('String literal continued on same line' in outcomeReason) > 0 THEN 'U|String literal continued on same line'
  WHEN POSITION('The query load is higher than the configured concurrency' in outcomeReason) > 0 THEN 'U|The query load is higher than the configured concurrency'
  WHEN POSITION('Subqueries used in expressions must be scalar (must return a single value)' in outcomeReason) > 0 THEN 'U|Subqueries used in expressions must be scalar (must return a single value)'
  WHEN POSITION('is not configured to support DML operations' in outcomeReason) > 0 THEN '?|Table T is not configured to support DML operations'
  WHEN POSITION('Table folder does not exists at path:' in outcomeReason) > 0 THEN '?|Table folder does not exists at path'
  WHEN POSITION('Table folder location can not be null' in outcomeReason) > 0 THEN '?|Table folder location can not be null'
  WHEN POSITION('doesn''t match with query schema' in outcomeReason) > 0 THEN '?|Table schema doesn''t match with query schema'
  WHEN POSITION('table''s field list and the table''s query field list have different counts.' in outcomeReason) > 0 THEN 'U|table''s field list and the table''s query field list have different counts.'
  WHEN POSITION('engine did not start. For more information, select the' in outcomeReason) > 0 THEN '?|The <engine> engine did not start'
  WHEN POSITION(' is not online.' in outcomeReason) > 0 THEN '?|The <engine> engine is not online'
  WHEN POSITION('The current location already contains a dataset named' in outcomeReason) > 0 THEN '?|The current location already contains a dataset named D'
  WHEN POSITION('has been deleted. Create a rule using a different engine under' in outcomeReason) > 0 THEN 'U|The engine <engine> has been deleted'
  WHEN POSITION('has been deleted. Select a different engine and try again.' in outcomeReason) > 0 THEN 'U|The engine <engine> has been deleted'
  WHEN POSITION('could not be identified. In order for automatic format detection to succeed, files must include a file extension' in outcomeReason) > 0 THEN '?|The file format for F could not be identified'
  WHEN POSITION('The function with a key,' in outcomeReason) > 0 THEN 'U|The function with a key K already exists'
  WHEN POSITION('The number of fields in values cannot exceed the number of fields in the schema.' in outcomeReason) > 0 THEN 'L|The number of fields in values cannot exceed the number of fields in the schema'
  WHEN POSITION('Number of fields in dataset exceeded the maximum number of fields of' in outcomeReason) > 0 THEN 'L|Number of fields in dataset exceeded the maximum number of fields of N'
  WHEN POSITION('The query planner ran out of internal resources and could not produce a query plan.' in outcomeReason) > 0 THEN 'D|The query planner ran out of internal resources and could not produce a query plan.'
  WHEN POSITION('The query load is higher than the configured concurrency' in outcomeReason) > 0 THEN '?|The query load is higher than the configured concurrency'
  WHEN POSITION('There already exists an entity of type' in outcomeReason) > 0 THEN 'U|There already exists an entity of type E at given path P'
  WHEN POSITION('There are not enough rules to produce a node with desired properties' in outcomeReason) > 0 THEN 'D|There are not enough rules to produce a node with desired properties'
  WHEN POSITION('There is no sheet with given name' in outcomeReason) > 0 THEN '?|There is no sheet with given name'
  WHEN POSITION('This daemon doesn''t support execution operations.' in outcomeReason) > 0 THEN 'D|This daemon doesn''t support execution operations'
  WHEN POSITION('This query cannot be decorrelated.' in outcomeReason) > 0 THEN '?|This query cannot be decorrelated'
  WHEN POSITION('possibly due to use of an unsupported feature.' in outcomeReason) > 0 THEN '?|This query cannot be planned - possibly due to use of an unsupported feature'
  WHEN POSITION('This type of window frame is currently not supported' in outcomeReason) > 0 THEN 'U|This type of window frame is currently not supported'
  WHEN POSITION('TimeoutException: Waited' in outcomeReason) > 0 THEN '?|TimeoutException'
  WHEN POSITION('Tried to access non-existent source' in outcomeReason) > 0 THEN 'U|Tried to access non-existent source'
  WHEN POSITION('Type conversion error for column' in outcomeReason) > 0 THEN 'U|Type conversion error for column C'
  WHEN POSITION('Type mismatch in column' in outcomeReason) > 0 THEN 'U|Type mismatch in column N of UNION [ALL]'
  WHEN POSITION('UNAVAILABLE: upstream connect error or disconnect/reset before headers.' in outcomeReason) > 0 THEN '?|UNAVAILABLE: upstream connect error or disconnect/reset before headers.'
  WHEN POSITION('UTF-16 files not supported' in outcomeReason) > 0 THEN 'L|UTF-16 files not supported'
  WHEN POSITION('Unable to choose a source.' in outcomeReason) > 0 THEN '?|Unable to choose a source. S was not specified and current context was not found'
  WHEN POSITION('Unable to coerce from the file''s data type' in outcomeReason) > 0 THEN 'U|Unable to coerce from the file''s data type T1 to the column''s data type T2'
  WHEN POSITION('Unable to complete query, attempting to union two datasets that have different underlying schemas.' in outcomeReason) > 0 THEN '?|Unable to complete query, attempting to union two datasets that have different underlying schemas'
  WHEN POSITION('Filesystem views are not supported.' in outcomeReason) > 0 THEN 'U|Unable to create/update/drop view. Filesystem views are not supported.'
  WHEN POSITION('Filesystem views are unsupported.' in outcomeReason) > 0 THEN 'U|Unable to create/update/drop view. Filesystem views are not supported.'
  WHEN POSITION('Please set the default warehouse location' in outcomeReason) > 0 THEN 'U|Unable to create table. Please set the default warehouse location'
  WHEN POSITION('Unable to determine output type for' in outcomeReason) > 0 THEN 'U|Unable to determine output type for F function.'
  WHEN POSITION('Unable to figure out engine to place query' in outcomeReason) > 0 THEN 'U|Unable to figure out engine to place query <query>'
  WHEN POSITION('Some virtual datasets were out of date and have been corrected.' in outcomeReason) > 0 THEN '?|Some virtual datasets were out of date and have been corrected'
  WHEN POSITION('The query timed out while waiting for engine' in outcomeReason) > 0 THEN '?|The query timed out while waiting for engine <engine>'
  WHEN POSITION('Please use a unique name for the new dataset.' in outcomeReason) > 0 THEN '?|The current location already contains a folder named F'
  WHEN POSITION('has been disabled. Enable the engine under Project Settings' in outcomeReason) > 0 THEN 'U|The engine <engine> has been disabled'
  WHEN POSITION('has disabled. Try again after enabling it.' in outcomeReason) > 0 THEN 'U|The engine <engine> has disabled. Try again after enabling it.'
  WHEN POSITION('Scaling up the engine replicas failed, please check the engine scaling events page for more details' in outcomeReason) > 0 THEN '?|Scaling up the engine replicas failed'
  WHEN POSITION('Unable to find the referenced field' in outcomeReason) > 0 THEN 'U|Unable to find the referenced field'
  WHEN POSITION('Unable to find table' in outcomeReason) > 0 THEN 'U|Unable to find table'
  WHEN POSITION('Unable to read table' in outcomeReason) > 0 THEN 'U|Unable to read table'
  WHEN POSITION('Refresh dataset command must include all partitions' in outcomeReason) > 0 THEN 'U|Refresh dataset command must include all partitions'
  WHEN POSITION('Unable to refresh dataset.' in outcomeReason) > 0 THEN '?|Unable to refresh dataset'
  WHEN POSITION(' in the virtual dataset.' in outcomeReason) > 0 THEN '?|Unable to find column <column> in the virtual dataset'
  WHEN POSITION('Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port' in outcomeReason) > 0 THEN 'U|Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port'
  WHEN POSITION('Unexpected mismatch of column names, expected' in outcomeReason) > 0 THEN 'U|Unexpected mismatch of column names'
  WHEN POSITION('Unimplemented syntax: SPECIAL for' in outcomeReason) > 0 THEN 'U|Unimplemented syntax: SPECIAL for ...'
  WHEN POSITION('Unknown format type for table' in outcomeReason) > 0 THEN 'U|Unknown format type for table <table>'
  WHEN POSITION('Unknown function ' in outcomeReason) > 0 THEN 'U|Unknown function F/with name/type'
  WHEN POSITION('Unknown function ' in outcomeReason) > 0 THEN 'U|Unknown function F/with name/type'
  WHEN POSITION('Unknown function ' in outcomeReason) > 0 THEN 'U|Unknown function F/with name/type'
  WHEN POSITION('Unknown identifier ''' in outcomeReason) > 0 THEN 'U|Unknown identifier I'
  WHEN POSITION('Unknown reflection id.' in outcomeReason) > 0 THEN '?|Unknown reflection id'
  WHEN POSITION('Unknown table [' in outcomeReason) > 0 THEN 'U|Unknown table T'
  WHEN POSITION('Unknown target column ''' in outcomeReason) > 0 THEN 'U|Unknown target column'
  WHEN POSITION('Unknown view [' in outcomeReason) > 0 THEN 'U|Unknown view V'
  WHEN POSITION('UnknownDBException:' in outcomeReason) > 0 THEN '?|UnknownDBException'
  WHEN POSITION('Unable to read data in column ' in outcomeReason) > 0 THEN '?|Unable to read data in column C'
  WHEN POSITION('Map, List and Union should not be used in group by, order by or in a comparison operator' in outcomeReason) > 0 THEN 'U|UnsupportedOperationException: Map, List and Union should not be used in group by, order by or in a comparison operator'
  WHEN POSITION('Addition of a new level dir is not allowed in incremental refresh' in outcomeReason) > 0 THEN 'U|UnsupportedOperationException: Addition of a new level dir is not allowed in incremental refresh'
  WHEN POSITION('Gandiva code generation is handled during build' in outcomeReason) > 0 THEN 'U|UnsupportedOperationException: Gandiva code generation is handled during build'
  WHEN POSITION('Failed to match SQL Operators for' in outcomeReason) > 0 THEN 'U|UnsupportedOperationException: Failed to match SQL Operators for ...'
  WHEN POSITION('Join only supports implicit casts between' in outcomeReason) > 0 THEN 'U|UnsupportedOperationException: Join only supports implicit casts between ...'
  WHEN POSITION('is not allowed to run REFRESH REFLECTION command.' in outcomeReason) > 0 THEN 'U|User U is not allowed to run REFRESH REFLECTION command'
  WHEN POSITION('User - Connection closed' in outcomeReason) > 0 THEN 'U|User - Connection closed'
  WHEN POSITION('User does not have access to [' in outcomeReason) > 0 THEN 'U|User does not have access to X'
  WHEN POSITION('is only supported against string literals and direct table references of types' in outcomeReason) > 0 THEN 'U|Using FUNCTION is only supported against string literals'
  WHEN POSITION('VACUUM TABLE command is not supported for this source' in outcomeReason) > 0 THEN 'U|VACUUM TABLE command is not supported for this source'
  WHEN POSITION('Cannot find field ' in outcomeReason) > 0 THEN 'U|Cannot find field ''F'' in struct'
  WHEN POSITION('A target row matched more than once. Please update your query.' in outcomeReason) > 0 THEN 'U|A target row matched more than once'
  WHEN POSITION('VALIDATION ERROR: The option ' in outcomeReason) > 0 THEN 'U|The option <option> does not exist'
  WHEN POSITION('Validation of view sql failed' in outcomeReason) > 0 THEN 'U|Validation of view sql failed'
  WHEN POSITION(' must be in the range [' in outcomeReason) > 0 THEN 'U|Value V for Y must be in the range [A,B]'
  WHEN POSITION('operator must have compatible types' in outcomeReason) > 0 THEN 'U|Values passed to <IN|VALUES|...> operator must have compatible types'
  WHEN POSITION('must be specified using AT SQL syntax' in outcomeReason) > 0 THEN 'U|Version context for table <table> must be specified using AT SQL syntax'
  WHEN POSITION('clause must be a condition' in outcomeReason) > 0 THEN 'U|C clause must be a condition'
  WHEN POSITION('Was not expecting value ''' in outcomeReason) > 0 THEN '?|Was not expecting value V for enumeration in this context'
  WHEN POSITION('While invoking method ''' in outcomeReason) > 0 THEN '?|While invoking method ...'
  WHEN POSITION('Windowed aggregate expression is illegal' in outcomeReason) > 0 THEN 'U|Windowed aggregate expression is illegal in C clause'
  WHEN POSITION('You''re trying to flatten a field that is not a list.' in outcomeReason) > 0 THEN 'U|You''re trying to flatten a field that is not a list'
  WHEN POSITION('Zone offset hours not in valid range: ' in outcomeReason) > 0 THEN 'U|Zone offset hours not in valid range: value V is not in the range X to Y '
  WHEN POSITION('] is not a VIEW' in outcomeReason) > 0 THEN 'U|X is [not] a TABLE/VIEW'
  WHEN POSITION('] is a VIEW' in outcomeReason) > 0 THEN 'U|X is [not] a TABLE/VIEW'
  WHEN POSITION('] does not exist' in outcomeReason) > 0 THEN 'U|Table T does not exist'
  WHEN POSITION('] is not a TABLE' in outcomeReason) > 0 THEN '?|X is [not] a TABLE/VIEW'
  WHEN POSITION('cast function for type' in outcomeReason) > 0 THEN '?|cast function for type T is not defined'
  WHEN POSITION('class com.dremio.exec.planner.sql.parser.CompoundIdentifier: ' in outcomeReason) > 0 THEN '?|class com.dremio.exec.planner.sql.parser.CompoundIdentifier'
  WHEN POSITION('class com.dremio.exec.planner.sql.parser.' in outcomeReason) > 0 THEN '?|class com.dremio.exec.planner.sql.parser'
  WHEN POSITION('class org.apache.calcite.sql.SqlBasicCall' in outcomeReason) > 0 THEN '?|class org.apache.calcite.sql.SqlBasicCall'
  WHEN POSITION('class org.apache.calcite.sql.SqlNodeList' in outcomeReason) > 0 THEN '?|class org.apache.calcite.sql.SqlNodeList'
  WHEN POSITION('class org.apache.calcite.sql.' in outcomeReason) > 0 THEN '?|class org.apache.calcite.sql'
  WHEN POSITION('cannot be cast to' in outcomeReason) > 0 THEN '?|T1 cannot be cast to T2'
  WHEN POSITION(', table not found.' in outcomeReason) > 0 THEN 'U|Table T not found'
  WHEN POSITION('UnAuthenticatedException: Unable to authenticate to the Nessie server.' in outcomeReason) > 0 THEN '?|UnAuthenticatedException: Unable to authenticate to the Nessie server.'
  WHEN POSITION('java.io.FileNotFoundException: No such file or directory:' in outcomeReason) > 0 THEN '?|FileNotFoundException'
  WHEN POSITION('Plugin tag has changed since refresh started.' in outcomeReason) > 0 THEN '?|Plugin tag has changed since refresh started.'
  WHEN POSITION('not a valid physical dataset' in outcomeReason) > 0 THEN '?|not a valid physical dataset'
  WHEN POSITION('one or more elements on the path are not found in namespace:' in outcomeReason) > 0 THEN '?|one or more elements on the path are not found in namespace'
  WHEN POSITION('because Glue cannot find the requested entity' in outcomeReason) > 0 THEN '?|because Glue cannot find the requested entity'
  WHEN POSITION('FileSystem is closed!' in outcomeReason) > 0 THEN '?|FileSystem is closed!'
  WHEN POSITION('tried to update version' in outcomeReason) > 0 THEN '?|tried to update version V1, found previous version V2'
  WHEN POSITION(', expected one of' in outcomeReason) > 0 THEN '?|unknown type %s, expected one of %s'

  WHEN POSITION('UnknownHostException' in outcomeReason) > 0 THEN 'U|UnknownHostException (too generic)'
  WHEN POSITION('already exists.' in outcomeReason) > 0 THEN 'U|Already exists'
  WHEN POSITION('already exists.' in outcomeReason) > 0 THEN 'U|Already exists'
  WHEN POSITION('An internal error occurred while running the query' in outcomeReason) > 0 THEN '?|An internal error occurred while running the query'
  WHEN POSITION('AssertionError' in outcomeReason) > 0 THEN '?|AssertionError'
  WHEN POSITION('ChannelClosedException:' in outcomeReason) > 0 THEN '?|ChannelClosedException'
  WHEN POSITION('CommitFailedException' in outcomeReason) > 0 THEN '?|CommitFailedException'
  WHEN POSITION('CONCURRENT_MODIFICATION ERROR' in outcomeReason) > 0 THEN '?|CME'
  WHEN POSITION('(com.microsoft.sqlserver.jdbc.SQLServerException)' in outcomeReason) > 0 THEN '?|com.microsoft.sqlserver.jdbc.SQLServerException (other)'
  WHEN POSITION('(net.snowflake.client.jdbc.SnowflakeSQLException)' in outcomeReason) > 0 THEN '?|net.snowflake.client.jdbc.SnowflakeSQLException (other)'
  WHEN POSITION('(net.snowflake.client.jdbc.SnowflakeSQLLoggedException)' in outcomeReason) > 0 THEN '?|net.snowflake.client.jdbc.SnowflakeSQLLoggedException (other)'
  WHEN POSITION('(org.postgresql.util.PSQLException)' in outcomeReason) > 0 THEN '?|org.postgresql.util.PSQLException (other)'
  WHEN POSITION('(com.amazon.redshift.util.RedshiftException)' in outcomeReason) > 0 THEN '?|com.amazon.redshift.util.RedshiftException (other)'
  WHEN POSITION('(java.sql.SQLException) ORA-' in outcomeReason) > 0 THEN '?|ORA-xxxxx java.sql.SQLException (other)'
  WHEN POSITION('org.mariadb.jdbc.export.ExceptionFactory.createException()' in outcomeReason) > 0 THEN '?|org.mariadb.jdbc.export.ExceptionFactory.createException() (other)'
  WHEN POSITION('DatasetNotFoundException' in outcomeReason) > 0 THEN '?|DatasetNotFoundException'
  WHEN POSITION('Encountered "' in outcomeReason) > 0 THEN 'U|Encoutered FOO at line X, column Y. Was expecting one of ...'
  WHEN POSITION('Error while expanding view' in outcomeReason) > 0 THEN '?|Error while expanding view'
  WHEN POSITION('Failed to load the Iceberg table' in outcomeReason) > 0 THEN '?|Failed to load the Iceberg table'
  WHEN POSITION('Failed to refresh the table' in outcomeReason) > 0 THEN '?|Failed to refresh the table'
  WHEN POSITION('Failure while retrieving dataset' in outcomeReason) > 0 THEN '?|Failure while retrieving dataset [D]'
  WHEN POSITION('FileNotFoundException' in outcomeReason) > 0 THEN '?|FileNotFoundException'
  WHEN POSITION('FlightRuntimeException' in outcomeReason) > 0 THEN '?|FlightRuntimeException'
  WHEN POSITION('GandivaException: ' in outcomeReason) > 0 THEN 'D|GandivaException (non-categorized)'
  WHEN POSITION('Grant failed. VIEW is not a valid privilege for project.' in outcomeReason) > 0 THEN 'U|Grant failed (user error)'
  WHEN POSITION('Grant failed:' in outcomeReason) > 0 THEN '?|Grant failed'
  WHEN POSITION('IOException' in outcomeReason) > 0 THEN '?|IOException'
  WHEN POSITION('IllegalArgumentException' in outcomeReason) > 0 THEN '?|IllegalArgumentException'
  WHEN POSITION('IllegalStateException' in outcomeReason) > 0 THEN '?|IllegalStateException (other)'
  WHEN POSITION('IndexOutOfBoundsException' in outcomeReason) > 0 THEN '?|IndexOutOfBoundsException'
  WHEN POSITION('IndexOutOfBoundsException:' in outcomeReason) > 0 THEN '?|IndexOutOfBoundsException'
  WHEN POSITION('InvalidCacheLoadException' in outcomeReason) > 0 THEN 'D|InvalidCacheLoadException'
  WHEN POSITION('org.apache.http.NoHttpResponseException' in outcomeReason) > 0 THEN '?|NoHttpResponseException'
  WHEN POSITION('DiskErrorException' in outcomeReason) > 0 THEN '?|DiskErrorException'
  WHEN POSITION('NumberFormatException' in outcomeReason) > 0 THEN 'U|NumberFormatException'
  WHEN POSITION('RejectedExecutionException' in outcomeReason) > 0 THEN 'D|RejectedExecutionException'
  WHEN POSITION('RocksDBException' in outcomeReason) > 0 THEN 'D|RocksDBException'
  WHEN POSITION('UnsupportedCharsetException' in outcomeReason) > 0 THEN '?|UnsupportedCharsetException'
  WHEN POSITION('(java.lang.NullPointerException) null' in outcomeReason) > 0 THEN '?|NPE'
  WHEN POSITION('NullPointerException' in outcomeReason) > 0 THEN '?|NPE'
  WHEN POSITION(''' not found' in outcomeReason) > 0 THEN '?|Object not found (very generic)'
  WHEN POSITION('" not found' in outcomeReason) > 0 THEN '?|Object not found (very generic)'
  WHEN POSITION('Ordinal out of range' in outcomeReason) > 0 THEN '?|Ordinal out of range'
  WHEN POSITION(''' returned error ''' in outcomeReason) > 0 THEN '?|Source ''<source>'' returned error ''<error>'''
  WHEN POSITION('Source branch' in outcomeReason) > 0 THEN '?|Source branch S1 not found in Source S2'
  WHEN POSITION('StackOverflowError' in outcomeReason) > 0 THEN '?|StackOverflowError'
  WHEN POSITION('StatusRuntimeException: UNKNOWN' in outcomeReason) > 0 THEN '?|StatusRuntimeException: UNKNOWN'
  WHEN POSITION('(io.grpc.StatusRuntimeException) UNKNOWN' in outcomeReason) > 0 THEN '?|StatusRuntimeException: UNKNOWN'
  WHEN POSITION('StatusRuntimeException' in outcomeReason) > 0 THEN '?|StatusRuntimeException'
  WHEN POSITION('] not found' in outcomeReason) > 0 THEN 'U|Table T not found'
  WHEN POSITION('] does not exist.' in outcomeReason) > 0 THEN '?|Table T does not exist'
  WHEN POSITION('] is currently unavailable. Info' in outcomeReason) > 0 THEN '?|The source S is currently unavailable. Metadata is not accessible.'
  WHEN POSITION('] is currently unavailable. Metadata' in outcomeReason) > 0 THEN '?|The source S is currently unavailable. Metadata is not accessible.'
  WHEN POSITION('TimeoutException' in outcomeReason) > 0 THEN '?|TimeoutException'
  WHEN POSITION('Unknown field ''' in outcomeReason) > 0 THEN '?|Unknown field F'
  WHEN POSITION('UnsupportedOperationException' in outcomeReason) > 0 THEN '?|UnsupportedOperationException'
  WHEN POSITION('ExecutionSetupException' in outcomeReason) > 0 THEN '?|ExecutionSetupException'
  WHEN POSITION('com.dremio.connector.ConnectorException' in outcomeReason) > 0 THEN '?|ConnectorException'
  WHEN POSITION('(org.apache.hadoop.fs.s3a.AWSClientIOException) getFileStatus on' in outcomeReason) > 0 THEN '?|Error during getFileStatus'
  WHEN POSITION('Error while getting dataset config' in outcomeReason) > 0 THEN '?|Error while getting dataset config'
  WHEN POSITION('while converting ' in outcomeReason) > 0 THEN '?|while converting ...'
  WHEN POSITION('OutOfMemoryError' in outcomeReason) > 0 THEN '?|OutOfMemoryError'
  WHEN POSITION('OutOfMemoryException' in outcomeReason) > 0 THEN '?|OutOfMemoryException'
  WHEN POSITION('Failure getting source [' in outcomeReason) > 0 THEN '?|Failure getting source [S]'
ELSE '?|Something else'
END as "category|error"
,*
FROM "aws-s3"."kamlesh-rsa"."wells-fargo"."queries-json"."fdlz-datascience"
where queueName != ''